version: '3'
services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=internet
      - POSTGRES_USER=maria
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d

  app:
    build:
      context: app
    volumes:
      - ./app/log:/tmp/mylog
    depends_on:
        - db
